Remove retina settings
ProjectPythia/cmip6-cookbook pull request #32
Opened 2022-12-05 22:00 UTC by mgrover1

Remove the retina settings which are causing notebook failure

2022-12-08 04:54 UTC, r-ford requested changes
[It looks like it's having a problem with](https://github.com/ProjectPythia/cmip6-cookbook/actions/runs/3624466523/jobs/6111476460#step:11:201)
```
x = x[~np.isnan(x)]
y = y[~np.isnan(y)]
```
I checked the data and didn't see any `nan`s, so these lines can probably be removed without issue.

2022-12-09 22:39 UTC, mgrover1 commented
@r-ford I made that change

2022-12-19 20:45 UTC, r-ford approved these changes

2023-04-04 14:39 UTC, mgrover1 commented
Closing since we fixed this in other PRs

2023-04-04 14:39 UTC, closed without merging